platform :ios, '10.0'
use_frameworks!

target '<%= appName %>' do
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'GoogleSignIn'
    pod 'FBSDKLoginKit'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end
