platform :ios, '10.0'
use_frameworks!

target '<%= appName %>' do
    pod 'GGARest',:git => 'https://github.com/greengrowapps/GGARest-iOS.git'
    pod 'GoogleSignIn'
    pod 'FBSDKLoginKit'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end
